### ISSUE TITLE
Chicken Nests Can't Be Shift + Clicked In

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#22]
Whenever you attempt to shift + click items into or out of a chicken nest, the game crashes with this message:

`java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(NonNullList.java:48)
	at com.team.kalstuff.tileentity.TileEntityChickenNest.setInventorySlotContents(TileEntityChickenNest.java:121)
	at net.minecraft.inventory.Slot.putStack(Slot.java:97)
	at com.team.kalstuff.container.ContainerChickenNest.transferStackInSlot(ContainerChickenNest.java:116)`

It seems to be a problem with TileEntityChickenNest. I fixed a similar problem that gave the same error there by updating some methods to the new versions in TileEntityHopper in 1.11. If anyone can fix this, please do.

**Comment by ParkerMc** [comment]
I will look at it soon it looks be simpleish.

**Comment by Kalman98** [comment]
It _should_ be....

**Comment by Kalman98** [comment]
Hooray!
